bot-token: "BOTTOKEN"
server-id: "000000000000000000"

staff-list: [ "GreenCreepyGhost", "Cubemaster02", "PokedonGCG", "Cobethel", "EchoEnvoyer", "Anjulah", "scoutblade", "Nindroid" ]

mall-remind-msg: Hello, mall re-rental has begun! Please contact an online staff member to re-rent your stall, or do nothing and your stall will be emptied."

enable-username-sync: false

enable-vote-streaks: false