bot-token: "BOTTOKEN"
server-id: "000000000000000000"

mod-list: 
  - Anjulah
  - PenguinPlays1235
  - Mc_BoogyWoogy
  - OceanSkys2222
  - scoutblade
  - Tand_
  - PokedonGCG

mod-plus-list:
  - EchoingStar
  - GreenCreepyGhost
  - Cubemaster02
  - Cobethel
  - Nindroid

mall-remind-msg: Hello, mall re-rental has begun! Please contact an online staff member to re-rent your stall, or do nothing and your stall will be emptied."

enable-username-sync: false
enable-vote-streaks: false
enable-buycraft-messages: false