bot-token: "BOTTOKEN"
server-id: "000000000000000000"

mod-list: 
  - Mod1
  - Mod2
  - Mod3

mod-plus-list:
  - ModPlus1
  - ModPlus2
  - Admin1
  - Admin2

mall-remind-msg: Hello, mall re-rental has begun! Please contact an online staff member to re-rent your stall, or do nothing and your stall will be emptied."

sync-reminder-msg: &7Your Discord Username is currently &a %DISCORDUSERNAME%. If you wish to update your username to match discord, use &a/sdu&7. To disable this warning, use &a/sdu reminder off&7.

botm-channel-id: "000000000000000000"
botm-banned-words:
  - anal
  - ass
  - asshole
  - ballsack
  - bastard
  - bitch
  - biatch
  - blowjob
  - boner
  - boob
  - boobs
  - bullshit
  - buttplug
  - clitoris
  - cock
  - crackwhore
  - cunt
  - cum
  - cyka
  - dick
  - dildo
  - dipshit
  - doggystyle
  - douche
  - dyke
  - earrape
  - fag
  - faggot
  - fuck
  - fucker
  - jerk
  - jizz
  - knobend
  - knobhead
  - knobjockey
  - marijuana
  - meth
  - minge
  - motherfucker
  - muff
  - penis
  - þorn
  - þornography
  - prick
  - pussy
  - queer
  - rape
  - retard
  - retarded
  - scrotum
  - slut
  - sperm
  - spunk
  - shit
  - shite
  - shitty
  - sussy
  - tit
  - tosser
  - turd
  - twat
  - penis
  - vagina
  - vibrator
  - wank
  - wanker
  - whore
  - omfg
  - wtf
  - uwu
  - onision
  - owo
  - 0w0
  - pussy
  - pussys
  - pussies