name: CashApp
version: 1.4.0
main: wyattduber.cashapp.CashApp
api-version: 1.21
author: wyattduber
website: https://www.github.com/wyattduber/CashApp
softdepend: [PlaceholderAPI, GriefPrevention]

commands:
  ca:
    description: Helper command for the CashApp plugin
    usage: /ca <args...>
    permission: ca.ca
    permission-message: §cYou do not have permission!
  botm:
    description: Command to send the BOTM message to the EA BOTM channel
    usage: /botm <username> <world> <x> <y> <z> <message...>
    permission: ca.botm
    permission-message: §cYou do not have permission!
  bce:
    description: Helper command for the buycraft plugin to email staff (buy craft event)
    usage: /bce <event id> <playername>
    permission: ca.bce
    permission-message: §cYou do not have permission!
  dnd:
    description: Command to toggle Do Not Disturb Status for the player!
    usage: /dnd <on/off> [player]
    permission: ca.dnd
    permission-message: §cYou do not have permission!
  rmd:
    description: Command to send all of the current users a reminder /mail
    usage: /rmd <username-1> <username-2> ... <username-n>
    permission: ca.rmd
    permission-message: §cYou do not have permission!
  sdu:
    description: Discord username sync command
    usage: /sdu <username> [#/unsync]
    permission: ca.sdu
    permission-message: §cYou do not have permission!
  getanarchyitem:
    description: Get one of the custom anarchy items
    usage: /getAnarchyItem <item>
    permission: ca.getanarchyitem
    permission-message: §cYou do not have permission!
  stats:
    description: Get the stats of a player
    usage: /stats <statType> <statSubType> [player]
    permission: ca.stats
    permission-message: §cYou do not have permission!

permissions:
  ca.*:
    description: Gives access to all CashApp Commands and Features
    children:
      ca.ca: true
      ca.update: true
      ca.botm: true
      ca.bce: true
      ca.dnd: true
      ca.rmd: true
      ca.ls: true
      ca.streak: true
      ca.getAnarchyItem: true
      ca.stats: true
  ca.botm:
    description: Allows the use of the BOTM command
    default: op
  ca.ca:
    description: Allows the use of the /ca command
    default: op
  ca.bce:
    description: Allows the use of the /bce command
    default: op
  ca.dnd:
    description: Allows the use of the /dnd command
    default: op
  ca.dnd.others:
    description: Allows the user of the /dnd on other players
    default: op
  ca.rmd:
    description: Allows the use of the /rmd command
    default: op
  ca.sdu:
    description: Allows the use of the /sdu command
    default: op
  ca.getanarchyitem:
    description: Allows the use of the /getAnarchyItem command
    default: op
  ca.stats:
    description: Allows the use of the /stats command
    default: op