name: CashApp
version: 1.4.0
main: wyattduber.cashapp.CashApp
api-version: 1.21
author: wyattduber
website: https://www.github.com/wyattduber/CashApp
depend: [CMI, CMILib, GriefPrevention, PlaceholderAPI, WorldGuard]

commands:
  am:
    description: Command to send a message to all online admins
    usage: /am <message...>
    permission: ca.adminchat
    permission-message: §cYou do not have permission!
  ca:
    description: Helper command for the CashApp plugin
    usage: /ca <args...>
    permission: ca.ca
    permission-message: §cYou do not have permission!
  botm:
    description: Command to send the BOTM message to the EA BOTM channel
    usage: /botm <username> <world> <x> <y> <z> <message...>
    permission: ca.botm
    permission-message: §cYou do not have permission!
  bce:
    description: Helper command for the buycraft plugin to email staff (buy craft event)
    usage: /bce <event id> <playername>
    permission: ca.bce
    permission-message: §cYou do not have permission!
  dnd:
    description: Command to toggle Do Not Disturb Status for the player!
    usage: /dnd <on/off> [player]
    permission: ca.dnd
    permission-message: §cYou do not have permission!
  gc:
    description: Command to send a message to all online players
    usage: /gc <message>
    permission: ca.guidechat
    permission-message: §cYou do not have permission!
  rmd:
    description: Command to send all of the current users a reminder /mail
    usage: /rmd <username-1> <username-2> ... <username-n>
    permission: ca.rmd
    permission-message: §cYou do not have permission!
  getanarchyitem:
    description: Get one of the custom anarchy items
    usage: /getAnarchyItem <item/trophy> [trophyType] [player]
    permission: ca.getanarchyitem
    permission-message: §cYou do not have permission!
  setstalldesc:
    description: Set the description of a stall
    usage: /setStallDesc <stallID> <description>
    permission: ca.setstalldesc
    permission-message: §cYou do not have permission!

permissions:
  ca.*:
    description: Gives access to all CashApp Commands and Features
    children:
      ca.adminchat: true
      ca.ca: true
      ca.update: true
      ca.botm: true
      ca.bce: true
      ca.dnd: true
      ca.guidechat: true
      ca.rmd: true
      ca.getAnarchyItem: true
      ca.setstalldesc: true
  ca.adminchat:
    description: Allows the use of the /am command
    default: op
  ca.botm:
    description: Allows the use of the BOTM command
    default: op
  ca.ca:
    description: Allows the use of the /ca command
    default: op
  ca.bce:
    description: Allows the use of the /bce command
    default: op
  ca.dnd:
    description: Allows the use of the /dnd command
    default: op
  ca.dnd.others:
    description: Allows the user of the /dnd on other players
    default: op
  ca.guidechat:
    description: Allows the use of the /gc command
    default: op
  ca.rmd:
    description: Allows the use of the /rmd command
    default: op
  ca.getanarchyitem:
    description: Allows the use of the /getAnarchyItem command
    default: op
  ca.setstalldesc:
    description: Allows the use of the /setStallDesc command
    default: op