name: CashApp
version: 1.3.0
main: doubleyoucash.cashapp.CashApp
api-version: 1.20
author: Wcash
website: https://www.github.com/DoubleYouCash/CashApp
softdepend: [VotingPlugin, WorldGuard]

commands:
  ca:
    description: Helper command for the CashApp plugin
    usage: /ca <args...>
    permission: ca.ca
    permission-message: §cYou do not have permission!
  botm:
    description: Command to send the BOTM message to the EA BOTM channel
    usage: /botm <username> <world> <x> <y> <z> <message...>
    permission: ca.botm
    permission-message: §cYou do not have permission!
  bce:
    description: Helper command for the buycraft plugin to email staff (buy craft event)
    usage: /bce <event id> <playername>
    permission: ca.bce
    permission-message: §cYou do not have permission!
  rmd:
    description: Command to send all of the current users a reminder /mail
    usage: /rmd <username-1> <username-2> ... <username-n>
    permission: ca.rmd
    permission-message: §cYou do not have permission!
  streak:
    description: Parent command for all streak-related commands
    usage: /streak <subcommand> <arg1> <arg2...>
    permission: ca.streak
    permission-message: §cYou do not have permission!
  sdu:
    description: Discord username sync command
    usage: /sdu <username> [#/unsync]
    permission: ca.sdu
    permission-message: §cYou do not have permission!

permissions:
  ca.*:
    description: Gives access to all CashApp Commands and Features
    children:
      ca.ca: true
      ca.update: true
      ca.botm: true
      ca.bce: true
      ca.rmd: true
      ca.ls: true
      ca.streak: true
  ca.botm:
    description: Allows the use of the BOTM command
    default: op
  ca.ca:
    description: Allows the use of the /ca command
    default: op
  ca.update:
    description: Allows the user to see if the plugin can update
    default: op
  ca.bce:
    description: Allows the use of the /bce command
    default: op
  ca.rmd:
    description: Allows the use of the /rmd command
    default: op
  ca.streak:
    description: Allows the use of the /streak base command
    default: op
  ca.streak.basic:
    description: Allows the use of the basic commands
    default: op
    children:
      ca.streak.togglelogin: true
      ca.streak.totalvotes: true
      ca.streak.getvotes: true
      ca.streak.lastvote: true
  ca.streak.admin:
    description: Allows the use of admin commands
    default: op
    children:
      ca.streak.getvotes.others: true
      ca.streak.togglelogin.others: true
      ca.streak.totalvotes.others: true
      ca.streak.getstreak.others: true
      ca.streak.lastvote.others: true
  ca.streak.togglelogin:
    description: Allows the use of the togglelogin command
    default: op
  ca.streak.togglelogin.others:
    description: Allwos the use of the togglelogin command on other players
    default: op
  ca.streak.totalvotes:
    description: Allows the use of the totalvotes command
    default: op
  ca.streak.totalvotes.others:
    description: Allows the use of the totalvotes command on other players
    default: op
  ca.streak.getvotes:
    description: Allows the use of the getvotes command
    default: op
  ca.streak.getvotes.others:
    description: Allows the use of the getvotes command on other players
    default: op
  ca.streak.getstreak:
    description: Allows the use of the getstreak command
    default: op
  ca.streak.getstreak.others:
    description: Allows the use of the getstreak command on other players
    default: op
  ca.streak.lastvote:
    description: Allows the use of the lastvote command
    default: op
  ca.streak.lastvote.others:
    description: Allows the use of the lastvote command on others
    default: op
  ca.sdu:
    description: Allows the use of the /sdu command
    default: op
