package wyattduber.cashapp.enums;

public enum StatType {
    joins,
    leaves,
    mobsKilled,
    playersKilled,
    deaths,
    blocksBroken,
    blocksPlaced,
    moneyEarned,
    moneySpent,
    fishCaught,
    itemsCrafted,
    itemsEnchanted,
    itemsSmelted,
    itemsDropped,
    itemsPickedUp,
    foodEaten,
    potionsDrank,
    xpGained,
    xpLost,
    timesSlept,
    damageDealt,
    damageTaken,
    distanceWalked,
    distanceCrouched,
    distanceSprinted,
    distanceSwam,
    distanceClimbed,
    distanceFlown,
}
